# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-10 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToysModel',
            new_name='Toy',
        ),
    ]
